name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:

      action:
        description: "Terraform Action"
        required: true
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:

  terraform-deploy:

    runs-on: ubuntu-latest

    environment: production

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::947782089242:role/GitHub_Role
          aws-region: us-east-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init

      - name: Terraform Validate
        working-directory: environments/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: environments/dev
        run: terraform plan -input=false -var-file="terraform.tfvars"

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        working-directory: environments/dev
        run: |
          terraform apply \
          -auto-approve \
          -input=false \
          -var-file="terraform.tfvars"

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        working-directory: environments/dev
        run: |
          terraform destroy \
          -auto-approve \
          -input=false \
          -var-file="terraform.tfvars"
          #this is a file